### ISSUE TITLE
Rounding error issue in karma system

### ISSUE THREAD

**Issue by fkhan000** [fkhan000/COOPERate#9]
For some reason, when a user likes a review, the amount that gets added to the reviewer's karma score gets rounded to an int instead of a float.  This bug occurs in the updateKarma functoin in the User.java file.

<img width="605" alt="Karma_Rounding_Error" src="https://github.com/fkhan000/COOPERate/assets/78983433/88306e31-f475-42de-8254-1a93d01d83bd">

**Comment by hengnan** [comment]
Changed karma variable from int -> float inside the cooperate.sql file
